-- This module is the root of the Smooth4DimensionalPoincareConjectureCanonicalLaneLean Lean proof package.
import Smooth4DimensionalPoincareConjectureCanonicalLaneLean.Basic
import Smooth4DimensionalPoincareConjectureCanonicalLaneLean.SourcePackage
import Smooth4DimensionalPoincareConjectureCanonicalLaneLean.SourceDependencies
import Smooth4DimensionalPoincareConjectureCanonicalLaneLean.Formalization
import Smooth4DimensionalPoincareConjectureCanonicalLaneLean.ReviewerBridge
import Smooth4DimensionalPoincareConjectureCanonicalLaneLean.TheoremStatement
import Smooth4DimensionalPoincareConjectureCanonicalLaneLean.MathlibObjects
import Smooth4DimensionalPoincareConjectureCanonicalLaneLean.AdmissibleClass
import Smooth4DimensionalPoincareConjectureCanonicalLaneLean.Projection
import Smooth4DimensionalPoincareConjectureCanonicalLaneLean.BridgeLemmas
import Smooth4DimensionalPoincareConjectureCanonicalLaneLean.GateLemmas
import Smooth4DimensionalPoincareConjectureCanonicalLaneLean.FinalTheorem
import Smooth4DimensionalPoincareConjectureCanonicalLaneLean.MathlibStatement
import Smooth4DimensionalPoincareConjectureCanonicalLaneLean.SmoothFourTopologyLayer
